services:
  - type: web
    name: backend  # 可自定义，例如 blog-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application
    runtime: python 3.11
    region: oregon  # 可根据需要修改
